<!-- === Code for src/routes/admin/orders/+page.svelte (Larger Thumbnails H-24) === -->
<script lang="ts">
	import { supabase } from '$lib/supabaseClient';
	import { onMount } from 'svelte';

	interface OrderDetailItem { productId?: string; productName?: string; size?: string; quantity?: number; price?: number; imageUrl?: string; }
	interface Order { id: string; created_at: string; customer_name: string; customer_phone: string; customer_address: string; order_details: OrderDetailItem[] | null; status: string; total_price: number; }

	let orders: Order[] = [];
	let loading = true;
	let error: string | null = null;
	let selectedStatusFilter: string = 'new';
	const statuses = ['new', 'processing', 'shipped', 'cancelled', 'all'];
    let updatingStatus: { [orderId: string]: boolean } = {};
    let expandedOrders: { [key: string]: boolean } = {};

    function toggleOrderDetails(orderId: string) { expandedOrders[orderId] = !expandedOrders[orderId]; }

	async function fetchOrders() { if (loading && orders.length > 0 && Object.keys(expandedOrders).length > 0) loading = false; else loading = true; error = null; try { let query = supabase.from('orders').select('*').order('created_at', { ascending: false }); if (selectedStatusFilter !== 'all') { query = query.eq('status', selectedStatusFilter); } const { data, error: dbError } = await query; if (dbError) throw dbError; orders = data || []; } catch (err: any) { error = 'حدث خطأ أثناء جلب الطلبات: ' + err.message; console.error('Fetch orders error:', err); } finally { loading = false; } }
	async function updateStatus(orderId: string, newStatus: string) { if (!statuses.includes(newStatus) || newStatus === 'all') return; const orderToUpdate = orders.find(o => o.id === orderId); if (!orderToUpdate) { alert('لم يتم العثور على الطلب لتحديثه.'); return; } const oldStatus = orderToUpdate.status; if (oldStatus === newStatus) return; updatingStatus[orderId] = true; updatingStatus = updatingStatus; error = null; const detailsArray = orderToUpdate.order_details; let stockAdjustmentSuccessful = true; try { let stockChange = 0; if (newStatus === 'shipped' && (oldStatus === 'new' || oldStatus === 'processing')) { stockChange = -1; } else if (newStatus === 'cancelled' && (oldStatus === 'shipped' || oldStatus === 'processing')) { stockChange = 1; } if (stockChange !== 0 && detailsArray && detailsArray.length > 0) { for (const item of detailsArray) { const { productId, size, quantity } = item; if(productId && size && quantity && quantity > 0) { const currentQuantity = quantity * Math.abs(stockChange); const { data: productData, error: fetchErr } = await supabase .from('products') .select('sizes_stock') .eq('id', productId) .single(); if (fetchErr || !productData) throw new Error(`فشل جلب مخزون المنتج ${productId}: ${fetchErr?.message}`); const currentStock = productData.sizes_stock || {}; const currentSizeStock = currentStock[size] || 0; if (stockChange < 0 && currentSizeStock < currentQuantity) { throw new Error(`لا يمكن شحن الطلب. المخزون غير كاف للمقاس ${size}. المتوفر: ${currentSizeStock}`); } const newSizeStock = currentSizeStock + (quantity * stockChange); const newSizesStockData = { ...currentStock, [size]: newSizeStock }; const { error: stockErr } = await supabase .from('products') .update({ sizes_stock: newSizesStockData }) .match({ id: productId }); if (stockErr) throw new Error(`فشل تحديث المخزون: ${stockErr.message}`); } else { throw new Error(`!! تنبيه !! لم يتم تحديث المخزون للطلب ${orderId}.`); } } } } catch (stockErr: any) { stockAdjustmentSuccessful = false; console.error(`Stock adjust error for order ${orderId}:`, stockErr); error = `خطأ تحديث المخزون: ${stockErr.message}`; if (stockChange < 0) { updatingStatus[orderId] = false; updatingStatus = updatingStatus; return; } if (stockChange > 0) { alert(`!! تنبيه !! تم إلغاء الطلب ${orderId} ولكن فشل إرجاع المخزون. الخطأ: ${stockErr.message}`); } } if (stockAdjustmentSuccessful || stockChange >= 0) { try { const { error: statusUpdateError } = await supabase .from('orders') .update({ status: newStatus }) .match({ id: orderId }); if (statusUpdateError) throw statusUpdateError; orders = orders.map(o => o.id === orderId ? { ...o, status: newStatus } : o); } catch (err: any) { alert(`!! فشل تحديث الحالة ${orderId} !!`); console.error("Status update DB error:", err); fetchOrders(); } } updatingStatus[orderId] = false; updatingStatus = updatingStatus; }
	async function deleteOrder(orderId: string) { if (!confirm(`هل أنت متأكد من حذف الطلب رقم ${orderId}؟`)) return; updatingStatus[orderId] = true; updatingStatus = updatingStatus; try { const { error: deleteError } = await supabase.from('orders').delete().match({ id: orderId }); if (deleteError) throw deleteError; orders = orders.filter((o) => o.id !== orderId); delete expandedOrders[orderId]; expandedOrders = expandedOrders; } catch (err: any) { alert(`فشل حذف الطلب: ${err.message}`); console.error('Delete order error:', err); } finally { updatingStatus[orderId] = false; updatingStatus = updatingStatus; } }
	onMount(() => { const channel = supabase .channel('public:orders') .on<Order>( 'postgres_changes', { event: '*', schema: 'public', table: 'orders' }, (payload) => { fetchOrders(); } ) .subscribe(); return () => { supabase.removeChannel(channel); }; });
	$: fetchOrders(selectedStatusFilter);
</script>

<svelte:head><title>إدارة الطلبات - بعيد وقريب</title></svelte:head>

<div class="mb-6 flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"> <h2 class="text-2xl font-semibold text-purple-300/90 title-glow">📋 إدارة الطلبات</h2> <div class="flex items-center gap-2"> <label for="statusFilter" class="text-sm text-gray-300 flex-shrink-0">عرض حسب الحالة:</label> <select id="statusFilter" bind:value={selectedStatusFilter} class="input-field !w-auto !py-1.5 !text-sm !bg-gray-700/60 !border-gray-600" disabled={loading}> {#each statuses as statusValue} <option value={statusValue}> {#if statusValue === 'new'}جديد {:else if statusValue === 'processing'}قيد التجهيز {:else if statusValue === 'shipped'}تم الشحن {:else if statusValue === 'cancelled'}ملغي {:else if statusValue === 'all'}الكل {/if} </option> {/each} </select> </div> </div>

{#if loading && orders.length === 0} <p class="text-center text-purple-300/70 animate-pulse py-10">جاري تحميل الطلبات...</p>
{:else if error} <p class="rounded border border-red-700 bg-red-900/50 p-4 text-center text-red-300">{error}</p>
{:else if orders.length === 0 && !loading} <p class="rounded border border-gray-700 bg-gray-800/40 p-6 text-center text-xl text-gray-400"> 😕 لا توجد طلبات للعرض {selectedStatusFilter !== 'all' ? `بالحالة '${selectedStatusFilter}'` : ''}. </p>
{:else}
	<div class="overflow-x-auto rounded-lg border border-gray-700/50 bg-gray-950/30 shadow-md relative"> {#if loading && orders.length > 0} <div class="absolute inset-0 bg-black/50 flex items-center justify-center z-10 rounded-lg"> <p class="text-purple-300/70 animate-pulse">جاري التحديث...</p> </div> {/if}
		<table class="min-w-full table-auto text-sm text-left text-gray-300 align-top">
			<thead class="bg-gray-800/50 text-xs uppercase text-purple-300/80 sticky top-0 z-[5]"> <tr> <th scope="col" class="px-4 py-3 text-center w-28">المنتج الأول</th> <th scope="col" class="px-4 py-3 whitespace-nowrap">تاريخ الطلب</th> <th scope="col" class="px-4 py-3">اسم الزبون</th> <th scope="col" class="px-4 py-3">الهاتف</th> <th scope="col" class="px-4 py-3">العنوان</th> <th scope="col" class="px-4 py-3">تفاصيل المنتجات</th> <th scope="col" class="px-4 py-3 text-center">الحالة</th> <th scope="col" class="px-4 py-3 text-center whitespace-nowrap">إجراءات</th> </tr> </thead>
			<tbody class:opacity-50={loading}>
				{#each orders as order (order.id)}
					{@const firstItem = order.order_details?.[0]}
					{@const hasMultipleItems = order.order_details && order.order_details.length > 1}
					{@const isExpanded = !!expandedOrders[order.id]}
					<tr class="border-b border-gray-700/50 hover:bg-gray-800/60" class:opacity-40={updatingStatus[order.id]}>
						<td class="px-4 py-3 text-center"> {#if firstItem?.imageUrl} <img src={firstItem.imageUrl} alt={firstItem?.productName || 'Product'} class="h-14 w-14 object-cover rounded-md inline-block shadow-sm border border-gray-600"> {:else} <div class="h-14 w-14 bg-gray-700 rounded-md inline-flex items-center justify-center text-xs text-gray-500 border border-gray-600">?</div> {/if} </td>
						<td class="px-4 py-3 whitespace-nowrap">{new Date(order.created_at).toLocaleString('ar-EG', {dateStyle: 'short', timeStyle: 'short'})}</td>
						<td class="px-4 py-3">{order.customer_name}</td>
						<td class="px-4 py-3 whitespace-nowrap ltr-input">{order.customer_phone}</td>
                        <td class="px-4 py-3 text-xs">{order.customer_address}</td>
						<td class="px-4 py-3 align-top text-xs"> {#if order.order_details && Array.isArray(order.order_details)} <div class="space-y-2"> {#each order.order_details as item, i (item.productId + item.size)} <div class="flex items-start gap-2 py-1" class:border-t={i > 0} class:border-gray-700={i > 0} class:hidden={!isExpanded && i > 0} > <div class="flex-shrink-0"> {#if item.imageUrl} <img src={item.imageUrl} alt={item.productName || 'Item'} class="h-24 w-24 rounded object-cover border border-gray-600"> {:else} <div class="h-24 w-24 rounded bg-gray-700 border border-gray-600 flex items-center justify-center text-gray-500 text-lg">?</div> {/if} </div> <div class="flex-grow"> <span class="font-semibold text-white">{item?.productName || 'غير متوفر'}</span> <span class="text-gray-300">({item?.size || 'N/A'})</span> <div class="text-gray-400 mt-0.5"> <span>الكمية: {item?.quantity || 'N/A'}</span> <span class="mx-1">|</span> <span>السعر: {item?.price || 'N/A'}</span> </div> </div> </div> {/each} </div> {#if hasMultipleItems} <button on:click={() => toggleOrderDetails(order.id)} class="mt-2 text-xs text-purple-400 hover:text-purple-300 hover:underline"> {isExpanded ? 'إخفاء الكل' : `عرض الكل (${order.order_details.length})`} </button> {/if} <div class="mt-2 pt-2 border-t border-gray-600 text-right"> <span class="font-semibold text-sm text-purple-300">الإجمالي الكلي: {order.total_price} شيكل</span> </div> {:else} <span class="text-gray-500">لا توجد تفاصيل</span> {/if} </td>
                        <td class="px-4 py-3 text-center whitespace-nowrap"> <span class="px-2 py-0.5 rounded-full text-xs font-medium" class:bg-blue-900={order.status === 'new'} class:text-blue-200={order.status === 'new'} class:bg-yellow-800={order.status === 'processing'} class:text-yellow-100={order.status === 'processing'} class:bg-green-800={order.status === 'shipped'} class:text-green-100={order.status === 'shipped'} class:bg-red-800={order.status === 'cancelled'} class:text-red-200={order.status === 'cancelled'} > {#if order.status === 'new'}جديد {:else if order.status === 'processing'}قيد التجهيز {:else if order.status === 'shipped'}تم الشحن {:else if order.status === 'cancelled'}ملغي {:else}{order.status} {/if} </span> </td>
						<td class="px-4 py-3 text-center whitespace-nowrap space-y-2"> <select on:change={(e) => updateStatus(order.id, e.currentTarget.value)} value={order.status} class="input-field !w-full !py-1 !px-2 !text-xs !bg-gray-700/50 !border-gray-600 block" disabled={updatingStatus[order.id]}> {#each statuses.filter(s => s !== 'all') as statusValue} <option value={statusValue} selected={order.status === statusValue}> {#if statusValue === 'new'}جديد {:else if statusValue === 'processing'}قيد التجهيز {:else if statusValue === 'shipped'}تم الشحن {:else if statusValue === 'cancelled'}ملغي {/if} </option> {/each} </select> <button on:click={() => deleteOrder(order.id)} class="text-red-500 hover:text-red-400 text-xs block w-full text-center hover:underline transition duration-150 disabled:opacity-50" disabled={updatingStatus[order.id]}> حذف الطلب </button> </td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
{/if}

<style> .title-glow {	text-shadow: 0 0 8px rgba(216, 180, 254, 0.4); } .input-field { @apply block w-full rounded-lg border border-gray-700 bg-gray-800/80 p-2.5 text-sm text-white placeholder-gray-500 transition duration-150 focus:border-purple-500 focus:ring-1 focus:ring-purple-500 focus:outline-none; } .ltr-input { direction: ltr; text-align: left; } tbody td, tbody th { vertical-align: top; padding-top: 0.75rem; padding-bottom: 0.75rem; } </style>